import Head from "next/head";
import Wilder from "../components/Wilder";
import PageHeader from "../components/PageHeader";

const people = {
  name: 'Jane Doe',
  description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
  skills: [
    {title: 'html', votes: 5},
    {title: 'css', votes: 5},
    {title: 'javascript', votes: 5},
    {title: 'react', votes: 15}
  ]
}


const Home = ({wilders}) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageHeader title="Wilders Book" />
      <main className="max-w-6xl mx-auto">
        <h2 className="text-2xl font-bold my-5">Wilders</h2>
        <section className="flex flex-wrap gap-4">
          {wilders.map((wilder) => (
            <Wilder key={wilder._id} name={wilder.name} description={wilder.city} skills={wilder.skills} />
          ))}
        </section>
      </main>

      <footer>
      <div className="">
        <p>&copy; 2022 Wild Code School</p>
      </div>
    </footer>
    </div>
  );
};

export async function getStaticProps() {
  const res = await fetch('http://localhost:3000/api/wilder')
  const temps = await res.json()
  const wilders = temps.result

  return {
    props: {
      wilders,
    },
  }
}

export default Home;
